### ISSUE TITLE
大佬改成自己的laf以后，初始化数据以后，应用没有正常工作

### ISSUE THREAD

**Issue by xungegeblue** [zhuo-tech/nest#4]
<img width="1847" alt="image" src="https://user-images.githubusercontent.com/14339924/231820517-3ac245bb-21ea-4ec3-ab7d-2a1fd3d3289a.png">

<img width="487" alt="image" src="https://user-images.githubusercontent.com/14339924/231820587-1551d3e6-0b21-403f-a0a2-0d7591d28c4b.png">
我修改了这2个地方的配置，改成我自己的laf。
可是后台进得去，数据都查不出来，是否缺少云函数？

**Comment by hankeke** [comment]
1. 404 应该是你没有配置访问策略
2. 403 集合没有开发访问权限

[访问策略](https://doc.laf.run/guide/db/policy.html)
